/**
 * Theme source-of-truth preset library for editorial WeChat themes.
 * Descriptions live with presets so preview, selector, and tests read one source.
 */

export const RAW_THEME_PRESETS = {
  "wechat-default": {
    "name": "默认风格",
    "styles": {
      "container": "max-width: 740px; margin: 0 auto; padding: 10px 12px 20px 12px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.8 !important; color: #3f3f3f !important; background-color: #fff !important; word-wrap: break-word;",
      "h1": "font-size: 24px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 32px 0 16px; padding-bottom: 8px; border-bottom: 2px solid #3498db;",
      "h2": "font-size: 22px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 28px 0 14px; padding-left: 12px; border-left: 4px solid #3498db;",
      "h3": "font-size: 20px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 24px 0 12px;",
      "h4": "font-size: 18px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 20px 0 10px;",
      "h5": "font-size: 17px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 18px 0 9px;",
      "h6": "font-size: 16px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 16px 0 8px;",
      "p": "margin: 16px 0 !important; line-height: 1.8 !important; color: #3f3f3f !important;",
      "strong": "font-weight: 600; color: #2c3e50 !important;",
      "em": "font-style: italic; color: #555 !important;",
      "a": "color: #3498db !important; text-decoration: none; border-bottom: 1px solid #3498db;",
      "ul": "margin: 16px 0; padding-left: 24px;",
      "ol": "margin: 16px 0; padding-left: 24px;",
      "li": "margin: 8px 0; line-height: 1.8 !important;",
      "blockquote": "margin: 16px 0; padding: 8px 16px; background-color: #fafafa !important; border-left: 3px solid #999; color: #666 !important; line-height: 1.5 !important;",
      "code": "font-family: Consolas, Monaco, \"Courier New\", monospace; font-size: 14px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #e74c3c !important; border-radius: 3px;",
      "pre": "margin: 20px 0; padding: 16px; background-color: #2d2d2d !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important;",
      "hr": "margin: 32px 0; border: none; border-top: 1px solid #e0e0e0;",
      "img": "max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 20px auto; border-radius: 8px;",
      "table": "width: 100%; margin: 20px 0; border-collapse: collapse; font-size: 15px;",
      "th": "background-color: #f0f0f0 !important; padding: 10px; text-align: left; border: 1px solid #e0e0e0; font-weight: 600;",
      "td": "padding: 10px; border: 1px solid #e0e0e0;",
      "tr": "border-bottom: 1px solid #e0e0e0;"
    },
    "description": "通用稳妥的公众号默认版式，适合大多数信息型内容。"
  },
  "wechat": {
    "name": "公众号原生",
    "description": "原汁原味的官方绿底纹，满足传统阅读习惯的稳妥之选",
    "styles": {
      "container": "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;",
      "h1": "font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ",
      "h2": "font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
      "h3": "font-size: 21px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 28px 0 14px;",
      "h4": "font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
      "h5": "font-size: 17px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 20px 0 10px;",
      "h6": "font-size: 16px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 18px 0 9px;",
      "p": "margin: 18px 0 !important; line-height: 1.7 !important; color: #333333 !important;",
      "strong": "font-weight: 700; color: #07c160 !important; background-color: rgba(7,193,96,0.08); padding: 0 4px; border-radius: 4px;",
      "em": "font-style: italic; color: #666 !important;",
      "a": "color: #07c160 !important; text-decoration: none; border-bottom: 1px solid #07c160; padding-bottom: 1px;",
      "ul": "margin: 16px 0; padding-left: 28px;",
      "ol": "margin: 16px 0; padding-left: 28px;",
      "li": "margin: 8px 0; line-height: 1.7 !important; color: #333333 !important;",
      "blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #f0f7f2 !important; border-left: 4px solid #07c160; color: #555 !important; border-radius: 4px; ",
      "code": "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #f0f7f2 !important; color: #07c160 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
      "pre": "margin: 24px 0; padding: 20px; background-color: #f0f7f2 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
      "hr": "margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;",
      "img": "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
      "table": "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
      "th": "background-color: #f0f7f2 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333333 !important; border: 1px solid #d8e8dc;",
      "td": "padding: 12px 16px; border: 1px solid #d8e8dc; color: #333333 !important;",
      "tr": "border: none;"
    }
  },
  "latepost-depth": {
    "name": "晚点风格",
    "styles": {
      "container": "max-width: 700px; margin: 0 auto; padding: 16px 12px 36px 12px; font-family: -apple-system, BlinkMacSystemFont, \"PingFang SC\", \"Hiragino Sans GB\", \"Microsoft YaHei\", sans-serif; font-size: 17px; line-height: 1.8 !important; color: #1a1a1a !important; background-color: #fff !important; word-wrap: break-word;",
      "h1": "font-size: 26px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 36px 0 18px; padding-left: 16px; border-left: 5px solid #d32f2f; position: relative;",
      "h2": "font-size: 20px; font-weight: 600; color: #fff !important; line-height: 1.4 !important; margin: 32px 0 16px; padding: 12px 20px; background-color: #d32f2f !important; border-radius: 4px; position: relative;",
      "h3": "font-size: 18px; font-weight: 600; color: #d32f2f !important; line-height: 1.45 !important; margin: 28px 0 14px; padding-left: 14px; border-left: 4px solid #d32f2f; position: relative;",
      "h4": "font-size: 17px; font-weight: 600; color: #1a1a1a !important; line-height: 1.5 !important; margin: 24px 0 12px; padding: 6px 10px; background-color: #f5f5f5 !important; border-left: 3px solid #ff5252;",
      "h5": "font-size: 16px; font-weight: 600; color: #333 !important; line-height: 1.5 !important; margin: 20px 0 10px;",
      "h6": "font-size: 15px; font-weight: 500; color: #666 !important; line-height: 1.5 !important; margin: 18px 0 9px;",
      "p": "margin: 18px 0 !important; line-height: 1.85 !important; color: #1a1a1a !important;",
      "strong": "font-weight: 700; color: #d32f2f !important; background-color: rgba(211, 47, 47, 0.08) !important; padding: 2px 6px; border-radius: 3px;",
      "em": "font-style: italic; color: #666 !important;",
      "a": "color: #d32f2f !important; text-decoration: none; border-bottom: 1px solid #d32f2f;",
      "ul": "margin: 20px 0; padding-left: 28px; list-style-type: disc;",
      "ol": "margin: 20px 0; padding-left: 28px; list-style-type: decimal;",
      "li": "margin: 10px 0; line-height: 1.8 !important; color: #1a1a1a !important;",
      "blockquote": "margin: 20px 0; padding: 12px 18px; background-color: #f5f5f5 !important; border-left: 4px solid #d32f2f; color: #1a1a1a !important; font-size: 16px; line-height: 1.6 !important; position: relative; border-radius: 4px;",
      "code": "font-family: \"SF Mono\", Menlo, Consolas, monospace; font-size: 15px; padding: 3px 8px; background-color: #f5f5f5 !important; color: #d32f2f !important; border-radius: 4px; font-weight: 500;",
      "pre": "margin: 24px 0; padding: 18px; background-color: #2a2a2a !important; color: #f5f5f5 !important; border-radius: 6px; overflow-x: auto; line-height: 1.6 !important; border-left: 4px solid #d32f2f;",
      "hr": "margin: 36px auto; border: none; height: 2px; background: linear-gradient(to right, transparent, #d32f2f, transparent); max-width: 200px;",
      "img": "max-width: 100%; max-height: 500px !important; height: auto; display: block; margin: 24px auto; border-radius: 6px; border: 2px solid #d32f2f; box-shadow: 0 4px 12px rgba(211, 47, 47, 0.12);",
      "table": "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 16px; border-radius: 6px; overflow: hidden;",
      "th": "background-color: #d32f2f !important; color: #fff !important; padding: 10px 14px; text-align: left; font-weight: 600; border: none;",
      "td": "padding: 10px 14px; border: none; border-bottom: 1px solid #e0e0e0; color: #1a1a1a !important; background-color: #fff !important;",
      "tr": "border-bottom: 1px solid #e0e0e0;"
    },
    "description": "更强的结构层级和论点推进，适合趋势判断和深度分析。"
  },
  "wechat-anthropic": {
    "name": "Claude",
    "styles": {
      "container": "max-width: 700px; margin: 0 auto; padding: 20px 24px 40px 24px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Helvetica Neue\", Arial, sans-serif; font-size: 17px; line-height: 1.75 !important; color: #2b2b2b !important; background-color: #faf9f7 !important; word-wrap: break-word; letter-spacing: -0.01em;",
      "h1": "font-size: 32px; font-weight: 600; color: #C15F3C !important; line-height: 1.2 !important; margin: 36px 0 18px; letter-spacing: -0.02em; background: linear-gradient(135deg, #C15F3C 0%, #e97d5b 50%, #CC8B7A 100%); -webkit-background-clip: text; background-clip: text;",
      "h2": "font-size: 26px; font-weight: 600; color: #C15F3C !important; line-height: 1.25 !important; margin: 32px 0 16px; letter-spacing: -0.015em; background: linear-gradient(135deg, #C15F3C 0%, #9DC88D 100%); -webkit-background-clip: text; background-clip: text;",
      "h3": "font-size: 22px; font-weight: 600; color: #2b2b2b !important; line-height: 1.3 !important; margin: 28px 0 14px; letter-spacing: -0.01em;",
      "h4": "font-size: 19px; font-weight: 600; color: #3a3a3a !important; line-height: 1.35 !important; margin: 24px 0 12px; letter-spacing: -0.01em;",
      "h5": "font-size: 17px; font-weight: 600; color: #4a4a4a !important; line-height: 1.4 !important; margin: 20px 0 10px;",
      "h6": "font-size: 16px; font-weight: 600; color: #5a5a5a !important; line-height: 1.45 !important; margin: 18px 0 9px;",
      "p": "margin: 20px 0 !important; line-height: 1.8 !important; color: #2b2b2b !important; font-size: 17px; letter-spacing: -0.005em;",
      "strong": "font-weight: 600; color: #C15F3C !important; background-color: rgba(193, 95, 60, 0.08) !important; padding: 2px 6px; border-radius: 3px;",
      "em": "font-style: italic; color: #5a5a5a !important;",
      "a": "color: #C15F3C !important; text-decoration: none; border-bottom: 1px solid rgba(193, 95, 60, 0.4); font-weight: 500;",
      "ul": "margin: 20px 0; padding-left: 28px;",
      "ol": "margin: 20px 0; padding-left: 28px;",
      "li": "margin: 10px 0; line-height: 1.8 !important; color: #2b2b2b !important; font-size: 17px;",
      "blockquote": "margin: 18px 0; padding: 10px 16px; background: linear-gradient(135deg, rgba(193, 95, 60, 0.06) 0%, rgba(157, 200, 141, 0.06) 100%); border-left: 4px solid #C15F3C; color: #2b2b2b !important; font-size: 17px; line-height: 1.6 !important; font-style: italic; border-radius: 6px;",
      "code": "font-family: \"SF Mono\", Consolas, Monaco, monospace; font-size: 15px; padding: 2px 6px; background-color: rgba(193, 95, 60, 0.08) !important; color: #C15F3C !important; border-radius: 6px; font-weight: 500; border: 1px solid rgba(193, 95, 60, 0.15);",
      "pre": "margin: 24px 0; padding: 20px; background: linear-gradient(135deg, #2b2b2b 0%, #3a3a3a 100%); color: #f5f5f5 !important; border-radius: 10px; overflow-x: auto; line-height: 1.55 !important; box-shadow: 0 4px 16px rgba(193, 95, 60, 0.12);",
      "hr": "margin: 36px auto; border: none; height: 2px; background: linear-gradient(to right, transparent, rgba(193, 95, 60, 0.3), rgba(157, 200, 141, 0.3), transparent); max-width: 200px;",
      "img": "max-width: 100%; max-height: 500px !important; height: auto; display: block; margin: 24px auto; border-radius: 10px; box-shadow: 0 6px 24px rgba(193, 95, 60, 0.1);",
      "table": "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 16px; border-radius: 8px; overflow: hidden;",
      "th": "background: linear-gradient(135deg, rgba(193, 95, 60, 0.08) 0%, rgba(157, 200, 141, 0.08) 100%); padding: 12px 16px; text-align: left; border: none; font-weight: 600; color: #2b2b2b !important; border-bottom: 2px solid rgba(193, 95, 60, 0.2);",
      "td": "padding: 12px 16px; border: none; border-bottom: 1px solid rgba(193, 95, 60, 0.1); color: #2b2b2b !important;",
      "tr": "border: none;"
    },
    "description": "更柔和的人文科技感，适合反思、随笔和创作者表达。"
  },
  "wechat-tech": {
    "name": "技术风格",
    "styles": {
      "container": "max-width: 740px; margin: 0 auto; padding: 10px 20px 20px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.75 !important; color: #2c3e50 !important; background-color: #fff !important; word-wrap: break-word;",
      "h1": "font-size: 26px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 36px 0 18px; padding: 0 0 12px; border-bottom: 3px solid #0066cc;",
      "h2": "font-size: 22px; font-weight: 700; color: #1a1a1a !important; line-height: 1.3 !important; margin: 32px 0 16px; padding-left: 16px; padding-top: 4px; padding-bottom: 4px; border-left: 5px solid #00a67d; background: linear-gradient(to right, #f0f9ff 0%, transparent 100%);",
      "h3": "font-size: 20px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 28px 0 14px; padding-left: 12px; border-left: 3px solid #ff9800;",
      "h4": "font-size: 18px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 24px 0 12px;",
      "h5": "font-size: 17px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 20px 0 10px;",
      "h6": "font-size: 16px; font-weight: 600; color: #34495e !important; line-height: 1.4 !important; margin: 18px 0 9px;",
      "p": "margin: 18px 0 !important; line-height: 1.8 !important; color: #3a3a3a !important;",
      "strong": "font-weight: 700; color: #1a1a1a !important; background-color: #fff3cd !important; padding: 2px 4px; border-radius: 8px;",
      "em": "font-style: italic; color: #666 !important;",
      "a": "color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc;",
      "ul": "margin: 18px 0; padding-left: 28px;",
      "ol": "margin: 18px 0; padding-left: 28px;",
      "li": "margin: 10px 0; line-height: 1.8 !important; color: #3a3a3a !important;",
      "blockquote": "margin: 16px 0; padding: 8px 16px; background-color: #f5f9fc !important; border-left: 3px solid #2196f3; color: #555 !important; line-height: 1.5 !important;",
      "code": "font-family: \"Fira Code\", Consolas, Monaco, \"Courier New\", monospace; font-size: 14px; padding: 3px 6px; background-color: #ffe6e6 !important; color: #d63031 !important; border-radius: 8px; font-weight: 500;",
      "pre": "margin: 24px 0; padding: 20px; background-color: #1e1e1e !important; border-radius: 8px; overflow-x: auto; line-height: 1.6 !important; box-shadow: 0 2px 8px rgba(0,0,0,0.1);",
      "hr": "margin: 36px 0; border: none; height: 2px; background: linear-gradient(to right, transparent, #0066cc, transparent);",
      "img": "max-width: 100%; max-height: 600px !important; height: auto; display: block; margin: 24px auto; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);",
      "table": "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px; box-shadow: 0 1px 4px rgba(0,0,0,0.1);",
      "th": "background-color: #0066cc !important; color: #fff !important; padding: 12px; text-align: left; border: 1px solid #0052a3; font-weight: 600;",
      "td": "padding: 12px; border: 1px solid #e0e0e0; background-color: #fff !important;",
      "tr": "border-bottom: 1px solid #e0e0e0;"
    },
    "description": "清晰直接的技术表达框架，适合工具、方法和机制拆解。"
  },
  "wechat-medium": {
    "name": "Notion",
    "styles": {
      "container": "max-width: 680px; margin: 0 auto; padding: 20px 12px 40px 12px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 17px; line-height: 1.7 !important; color: #242424 !important; background-color: #fff !important; word-wrap: break-word; letter-spacing: -0.003em;",
      "h1": "font-size: 28px; font-weight: 700; color: #242424 !important; line-height: 1.2 !important; margin: 36px 0 18px; letter-spacing: -0.02em; font-family: Georgia, \"Times New Roman\", serif;",
      "h2": "font-size: 24px; font-weight: 700; color: #242424 !important; line-height: 1.25 !important; margin: 32px 0 16px; letter-spacing: -0.015em; font-family: Georgia, \"Times New Roman\", serif;",
      "h3": "font-size: 20px; font-weight: 700; color: #242424 !important; line-height: 1.3 !important; margin: 28px 0 14px; letter-spacing: -0.01em; font-family: Georgia, \"Times New Roman\", serif;",
      "h4": "font-size: 18px; font-weight: 700; color: #242424 !important; line-height: 1.35 !important; margin: 24px 0 12px; font-family: Georgia, \"Times New Roman\", serif;",
      "h5": "font-size: 17px; font-weight: 700; color: #242424 !important; line-height: 1.4 !important; margin: 20px 0 10px; font-family: Georgia, \"Times New Roman\", serif;",
      "h6": "font-size: 16px; font-weight: 700; color: #242424 !important; line-height: 1.4 !important; margin: 18px 0 9px; font-family: Georgia, \"Times New Roman\", serif;",
      "p": "margin: 20px 0 !important; line-height: 1.75 !important; color: #242424 !important; font-size: 17px; letter-spacing: -0.003em;",
      "strong": "font-weight: 700; color: #242424 !important;",
      "em": "font-style: italic; color: #242424 !important;",
      "a": "color: #242424 !important; text-decoration: none; border-bottom: 1px solid #242424;",
      "ul": "margin: 20px 0; padding-left: 32px;",
      "ol": "margin: 20px 0; padding-left: 32px;",
      "li": "margin: 10px 0; line-height: 1.7 !important; color: #242424 !important; font-size: 17px;",
      "blockquote": "margin: 20px 0; padding: 0 20px; border-left: 3px solid #242424; color: #242424 !important; font-size: 17px; line-height: 1.6 !important; font-style: italic; font-family: Georgia, \"Times New Roman\", serif;",
      "code": "font-family: Menlo, Monaco, \"Courier New\", monospace; font-size: 15px; padding: 2px 6px; background-color: #f5f5f5 !important; color: #d73a49 !important; border-radius: 3px;",
      "pre": "margin: 24px 0; padding: 20px; background-color: #f7f7f7 !important; border-radius: 8px; overflow-x: auto; line-height: 1.5 !important;",
      "hr": "margin: 36px auto; border: none; text-align: center; height: 1px; background-color: #e6e6e6 !important; max-width: 300px;",
      "img": "max-width: 100%; max-height: 500px !important; height: auto; display: block; margin: 24px auto;",
      "table": "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 16px;",
      "th": "background-color: #f7f7f7 !important; padding: 10px 14px; text-align: left; border-bottom: 2px solid #e6e6e6; font-weight: 700; color: #242424 !important;",
      "td": "padding: 10px 14px; border-bottom: 1px solid #e6e6e6; color: #242424 !important;",
      "tr": "border: none;"
    },
    "description": "干净克制的知识库写作版式，适合笔记、文档和结构化表达。"
  },
  "hische-editorial": {
    "name": "Hische·编辑部",
    "styles": {
      "container": "max-width: 700px; margin: 0 auto; padding: 20px 20px 50px 20px; font-family: \"Crimson Text\", Garamond, serif; font-size: 17px; line-height: 1.75 !important; color: #2c2c2c !important; background-color: #fffef9 !important; word-wrap: break-word;",
      "h1": "font-size: 32px; font-weight: 400; color: #c9302c !important; line-height: 1.2 !important; margin: 36px 0 18px; letter-spacing: -0.02em; font-family: \"Bodoni MT\", \"Didot\", serif; text-align: center;",
      "h2": "font-size: 26px; font-weight: 400; color: #2c2c2c !important; line-height: 1.25 !important; margin: 32px 0 16px; letter-spacing: -0.015em; font-family: \"Bodoni MT\", \"Didot\", serif; border-top: 1px solid #c9302c; border-bottom: 1px solid #c9302c; padding: 10px 0; text-align: center;",
      "h3": "font-size: 21px; font-weight: 400; color: #2c2c2c !important; line-height: 1.3 !important; margin: 28px 0 14px; font-family: \"Bodoni MT\", \"Didot\", serif;",
      "h4": "font-size: 17px; font-weight: 600; color: #2c2c2c !important; line-height: 1.35 !important; margin: 24px 0 12px; text-transform: uppercase; letter-spacing: 0.05em;",
      "h5": "font-size: 16px; font-weight: 400; color: #2c2c2c !important; line-height: 1.4 !important; margin: 20px 0 10px; font-style: italic;",
      "h6": "font-size: 15px; font-weight: 400; color: #666 !important; line-height: 1.45 !important; margin: 18px 0 9px;",
      "p": "margin: 20px 0 !important; line-height: 1.8 !important; color: #2c2c2c !important; text-align: justify;",
      "strong": "font-weight: 700; color: #c9302c !important; letter-spacing: 0.02em;",
      "em": "font-style: italic; color: #2c2c2c !important;",
      "a": "color: #c9302c !important; text-decoration: none; border-bottom: 1px solid #c9302c;",
      "ul": "margin: 20px 0; padding-left: 25px; list-style: disc;",
      "ol": "margin: 20px 0; padding-left: 25px;",
      "li": "margin: 10px 0; line-height: 1.75 !important; color: #2c2c2c !important;",
      "blockquote": "margin: 20px 0; padding: 0 24px; background-color: transparent !important; border-left: none; color: #2c2c2c !important; font-size: 17px; line-height: 1.55 !important; font-style: italic; text-align: center; font-family: \"Bodoni MT\", \"Didot\", serif;",
      "code": "font-family: \"Courier Prime\", monospace; font-size: 15px; padding: 2px 6px; background-color: #f9f9f9 !important; color: #c9302c !important; border: 1px solid #e0e0e0;",
      "pre": "margin: 24px 0; padding: 20px; background-color: #f9f9f9 !important; border-left: 4px solid #c9302c; overflow-x: auto; line-height: 1.6 !important;",
      "hr": "margin: 36px auto; border: none; height: 1px; background-color: #c9302c !important; max-width: 100px;",
      "img": "max-width: 100%; max-height: 500px !important; height: auto; display: block; margin: 24px auto; border: 1px solid #e0e0e0;",
      "table": "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 16px;",
      "th": "background-color: #f9f9f9 !important; padding: 10px 12px; text-align: left; border-top: 2px solid #c9302c; border-bottom: 2px solid #c9302c; font-weight: 700; color: #2c2c2c !important; text-transform: uppercase; letter-spacing: 0.05em; font-size: 14px;",
      "td": "padding: 10px 12px; border-bottom: 1px solid #e0e0e0; color: #2c2c2c !important;",
      "tr": "border-bottom: 1px solid #e0e0e0;"
    },
    "description": "更像杂志专栏或编辑页，适合品牌表达与故事性内容。"
  },
  "ando-concrete": {
    "name": "安藤·清水",
    "styles": {
      "container": "max-width: 600px; margin: 0 auto; padding: 20px 24px 50px 24px; font-family: \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.85 !important; color: #4a4a4a !important; background-color: #fff !important; word-wrap: break-word;",
      "h1": "font-size: 24px; font-weight: 300; color: #1a1a1a !important; line-height: 1.35 !important; margin: 36px 0 20px; padding-bottom: 16px; border-bottom: 1px solid #d0d0d0; letter-spacing: 0.15em; text-transform: uppercase;",
      "h2": "font-size: 18px; font-weight: 400; color: #2a2a2a !important; line-height: 1.45 !important; margin: 32px 0 16px; padding: 12px 0; border-top: 1px solid #e0e0e0; border-bottom: 1px solid #e0e0e0; letter-spacing: 0.1em; background-color: #fafafa !important;",
      "h3": "font-size: 16px; font-weight: 400; color: #3a3a3a !important; line-height: 1.5 !important; margin: 28px 0 14px; letter-spacing: 0.08em;",
      "h4": "font-size: 15px; font-weight: 500; color: #4a4a4a !important; line-height: 1.55 !important; margin: 24px 0 12px; letter-spacing: 0.05em;",
      "h5": "font-size: 14px; font-weight: 500; color: #5a5a5a !important; line-height: 1.55 !important; margin: 20px 0 10px;",
      "h6": "font-size: 13px; font-weight: 500; color: #6a6a6a !important; line-height: 1.55 !important; margin: 18px 0 9px;",
      "p": "margin: 20px 0 !important; line-height: 1.85 !important; color: #4a4a4a !important; text-align: justify;",
      "strong": "font-weight: 600; color: #1a1a1a !important; letter-spacing: 0.05em;",
      "em": "font-style: normal; color: #6a6a6a !important; letter-spacing: 0.05em; font-weight: 300;",
      "a": "color: #4a4a4a !important; text-decoration: none; border-bottom: 1px solid #b0b0b0; padding-bottom: 1px;",
      "ul": "margin: 20px 0; padding-left: 28px; list-style-type: circle;",
      "ol": "margin: 20px 0; padding-left: 28px; list-style-type: decimal;",
      "li": "margin: 10px 0; line-height: 1.85 !important; color: #4a4a4a !important; padding-left: 20px; position: relative;",
      "blockquote": "margin: 20px 0; padding: 14px 20px; background-color: #ffffff !important; border: 1px solid #d0d0d0; color: #3a3a3a !important; font-size: 15px; line-height: 1.7 !important; letter-spacing: 0.03em; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);",
      "code": "font-family: \"Courier New\", Courier, monospace; font-size: 14px; padding: 2px 6px; background-color: #f0f0f0 !important; color: #4a4a4a !important; border: 1px solid #d0d0d0;",
      "pre": "margin: 24px 0; padding: 20px; background-color: #2a2a2a !important; color: #f0f0f0 !important; border: none; overflow-x: auto; line-height: 1.6 !important; box-shadow: inset 0 0 30px rgba(0, 0, 0, 0.4);",
      "hr": "margin: 36px auto; border: none; width: 60px; height: 1px; background-color: #c0c0c0 !important;",
      "img": "max-width: 100%; max-height: 450px !important; height: auto; display: block; margin: 24px auto; filter: grayscale(20%); opacity: 0.95;",
      "table": "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 14px; border: 1px solid #d0d0d0;",
      "th": "background-color: #f8f8f8 !important; padding: 12px; text-align: left; border: 1px solid #d0d0d0; font-weight: 400; color: #2a2a2a !important; letter-spacing: 0.08em; text-transform: uppercase;",
      "td": "padding: 12px; border: 1px solid #e0e0e0; color: #4a4a4a !important; background-color: #fff !important;",
      "tr": "border: 1px solid #e0e0e0;"
    },
    "description": "偏建筑与理性秩序感，适合结构化思考与方法论文章。"
  },
  "gaudi-organic": {
    "name": "高迪·有机",
    "styles": {
      "container": "max-width: 700px; margin: 0 auto; padding: 20px 24px 45px 24px; font-family: \"Baskerville\", \"Georgia\", serif; font-size: 17px; line-height: 1.8 !important; color: #3d2914 !important; background-color: #fff5e6 !important; word-wrap: break-word;",
      "h1": "font-size: 32px; font-weight: 700; color: #ff6b6b !important; background: linear-gradient(45deg, #ff6b6b, #ffd93d, #6bcf7f, #4ecdc4, #5b86e5, #a55eea); -webkit-background-clip: text; background-clip: text; line-height: 1.25 !important; margin: 36px 0 18px; text-align: center; letter-spacing: -0.02em; position: relative; padding: 12px;",
      "h2": "font-size: 26px; font-weight: 600; color: #c0392b !important; line-height: 1.3 !important; margin: 32px 0 16px; text-align: center; position: relative; padding: 10px 20px; background: radial-gradient(ellipse at center, rgba(192, 57, 43, 0.08) 0%, transparent 70%); border-radius: 50% 20% / 10% 40%;",
      "h3": "font-size: 21px; font-weight: 600; color: #27ae60 !important; line-height: 1.35 !important; margin: 28px 0 14px; padding-left: 24px; position: relative; border-left: 4px wavy #27ae60;",
      "h4": "font-size: 18px; font-weight: 600; color: #2980b9 !important; line-height: 1.4 !important; margin: 24px 0 12px; padding: 8px 16px; background: linear-gradient(90deg, rgba(41, 128, 185, 0.1) 0%, transparent 50%); border-radius: 100px 0 100px 0;",
      "h5": "font-size: 17px; font-weight: 600; color: #8e44ad !important; line-height: 1.45 !important; margin: 20px 0 10px;",
      "h6": "font-size: 16px; font-weight: 600; color: #d35400 !important; line-height: 1.45 !important; margin: 18px 0 9px; font-style: italic;",
      "p": "margin: 20px 0 !important; line-height: 1.85 !important; color: #3d2914 !important; text-indent: 2em;",
      "strong": "font-weight: 700; color: #c0392b !important; background: linear-gradient(180deg, transparent 60%, rgba(192, 57, 43, 0.2) 60%); padding: 2px 4px;",
      "em": "font-style: italic; color: #27ae60 !important; font-weight: 500;",
      "a": "color: #2980b9 !important; text-decoration: none; border-bottom: 2px wavy #2980b9; position: relative;",
      "ul": "margin: 20px 0; padding-left: 28px; list-style-type: square;",
      "ol": "margin: 20px 0; padding-left: 28px; list-style-type: decimal;",
      "li": "margin: 10px 0; line-height: 1.8 !important; color: #3d2914 !important; padding: 10px 18px 10px 32px; position: relative; background: linear-gradient(90deg, rgba(255, 193, 7, 0.1) 0%, transparent 30%); border-radius: 20px 40px 80px 20px / 80px 20px 40px 20px;",
      "blockquote": "margin: 20px auto; padding: 16px 22px; background: radial-gradient(circle at top left, rgba(255, 107, 107, 0.1) 0%, rgba(109, 207, 127, 0.1) 25%, rgba(78, 205, 196, 0.1) 50%, rgba(91, 134, 229, 0.1) 75%, rgba(165, 94, 234, 0.1) 100%); border: 3px solid transparent; border-image: linear-gradient(45deg, #ff6b6b, #ffd93d, #6bcf7f, #4ecdc4, #5b86e5, #a55eea) 1; border-radius: 50% 20% / 10% 40%; color: #3d2914 !important; font-size: 17px; line-height: 1.6 !important; font-style: italic; text-align: center; max-width: 600px;",
      "code": "font-family: \"Courier New\", Courier, monospace; font-size: 15px; padding: 3px 8px; background: linear-gradient(45deg, rgba(255, 107, 107, 0.2), rgba(255, 217, 61, 0.2)); color: #c0392b !important; border-radius: 50% / 30%; font-weight: 600;",
      "pre": "margin: 24px 0; padding: 22px; background: linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #fda085 100%); color: #fff !important; border-radius: 30% 70% 70% 30% / 60% 40% 60% 40%; overflow-x: auto; line-height: 1.55 !important; box-shadow: 0 8px 24px rgba(0, 0, 0, 0.18); position: relative;",
      "hr": "margin: 36px auto; border: none; height: 24px; background: url(\"data:image/svg+xml,%3Csvg width='100' height='30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M0,15 Q25,0 50,15 T100,15' stroke='%23c0392b' stroke-width='2' fill='none'/%3E%3C/svg%3E\") repeat-x center; background-size: 80px 24px; max-width: 240px;",
      "img": "max-width: 100%; max-height: 500px !important; height: auto; display: block; margin: 24px auto; border-radius: 10px; box-shadow: 0 8px 20px rgba(255, 193, 7, 0.12); border: 2px solid #ffd93d;",
      "table": "width: 100%; margin: 24px 0; border-collapse: separate; border-spacing: 4px; font-size: 15px;",
      "th": "background: linear-gradient(45deg, #ff6b6b 0%, #ffd93d 100%); color: #fff !important; padding: 12px; text-align: left; font-weight: 600; border-radius: 12px 12px 0 0; text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.2);",
      "td": "padding: 10px; background: linear-gradient(135deg, rgba(255, 193, 7, 0.1) 0%, rgba(109, 207, 127, 0.1) 100%); color: #3d2914 !important; border-radius: 8px;",
      "tr": "border: none;"
    },
    "description": "更有装饰性和曲线感，适合创意、美学和灵感型内容。"
  },
  "nikkei": {
    "name": "Nikkei 日経",
    "styles": {
      "container": "max-width: 650px; margin: 0 auto; padding: 10px 12px 20px 12px; font-family: \"Hiragino Kaku Gothic ProN\", \"Yu Gothic\", \"Meiryo\", sans-serif; font-size: 15px; line-height: 1.6 !important; color: #1a1a1a !important; background-color: #fff !important; word-wrap: break-word;",
      "h1": "font-size: 24px; font-weight: 700; color: #000 !important; line-height: 1.3 !important; margin: 25px 0 15px; padding-bottom: 8px; border-bottom: 2px solid #000;",
      "h2": "font-size: 18px; font-weight: 700; color: #c41230 !important; line-height: 1.4 !important; margin: 20px 0 12px; padding-left: 10px; border-left: 3px solid #c41230;",
      "h3": "font-size: 16px; font-weight: 600; color: #000 !important; line-height: 1.4 !important; margin: 18px 0 10px; padding: 4px 8px; background-color: #f5f5f5 !important;",
      "h4": "font-size: 15px; font-weight: 600; color: #333 !important; line-height: 1.5 !important; margin: 15px 0 8px; text-decoration: underline; text-decoration-color: #c41230; text-underline-offset: 3px;",
      "h5": "font-size: 14px; font-weight: 600; color: #666 !important; line-height: 1.5 !important; margin: 12px 0 6px;",
      "h6": "font-size: 13px; font-weight: 600; color: #999 !important; line-height: 1.5 !important; margin: 10px 0 5px;",
      "p": "margin: 12px 0 !important; line-height: 1.6 !important; color: #1a1a1a !important; text-align: justify;",
      "strong": "font-weight: 700; color: #000 !important; background-color: #fff3f3 !important; padding: 0 2px;",
      "em": "font-style: normal; color: #c41230 !important; font-weight: 600;",
      "a": "color: #0066cc !important; text-decoration: none; border-bottom: 1px solid #0066cc;",
      "ul": "margin: 15px 0; padding-left: 28px; list-style-type: disc;",
      "ol": "margin: 15px 0; padding-left: 28px; list-style-type: decimal;",
      "li": "margin: 6px 0; line-height: 1.6 !important; color: #1a1a1a !important;",
      "blockquote": "margin: 16px 0; padding: 10px 15px; background-color: transparent !important; border-left: 2px solid #c41230; border-right: 2px solid #c41230; color: #1a1a1a !important; font-size: 14px; line-height: 1.5 !important;",
      "code": "font-family: \"Courier New\", monospace; font-size: 13px; padding: 2px 4px; background-color: #f5f5f5 !important; color: #c41230 !important;",
      "pre": "margin: 20px 0; padding: 15px; background-color: #f5f5f5 !important; border: 1px solid #ddd; overflow-x: auto; line-height: 1.4 !important;",
      "hr": "margin: 30px 0; border: none; height: 1px; background-color: #000 !important;",
      "img": "max-width: 100%; max-height: 400px !important; height: auto; display: block; margin: 20px auto; border: 1px solid #ddd;",
      "table": "width: 100%; margin: 20px 0; border-collapse: collapse; font-size: 14px; border: 1px solid #000;",
      "th": "background-color: #c41230 !important; color: #fff !important; padding: 8px 10px; text-align: left; font-weight: 600; border: 1px solid #c41230;",
      "td": "padding: 6px 10px; border: 1px solid #ddd; color: #1a1a1a !important; background-color: #fff !important;",
      "tr": "border-bottom: 1px solid #ddd;"
    },
    "description": "偏商业与技术分析的报刊感，适合产业、市场和研究内容。"
  },
  "warm-docs": {
    "name": "焦橙文档",
    "styles": {
      "container": "max-width: 700px; margin: 0 auto; padding: 16px 20px 40px 20px; font-family: -apple-system, BlinkMacSystemFont, \"PingFang SC\", \"Noto Sans SC\", \"Helvetica Neue\", sans-serif; font-size: 16px; line-height: 1.8 !important; color: #1A1A1A !important; background-color: #FAFAF9 !important; word-wrap: break-word;",
      "h1": "font-size: 28px; font-weight: 700; color: #1A1A1A !important; line-height: 1.3 !important; margin: 36px 0 12px; padding-bottom: 12px; border-bottom: 3px solid #C2410C;",
      "h2": "font-size: 22px; font-weight: 700; color: #1A1A1A !important; line-height: 1.35 !important; margin: 36px 0 14px; padding-top: 16px; border-top: 3px solid #C2410C;",
      "h3": "font-size: 18px; font-weight: 600; color: #1A1A1A !important; line-height: 1.4 !important; margin: 28px 0 12px; padding-left: 14px; border-left: 4px solid #C2410C;",
      "h4": "font-size: 16px; font-weight: 600; color: #C2410C !important; line-height: 1.45 !important; margin: 24px 0 10px;",
      "h5": "font-size: 15px; font-weight: 600; color: #6B6B6B !important; line-height: 1.5 !important; margin: 20px 0 8px;",
      "h6": "font-size: 14px; font-weight: 600; color: #6B6B6B !important; line-height: 1.5 !important; margin: 18px 0 8px;",
      "p": "margin: 18px 0 !important; line-height: 1.8 !important; color: #1A1A1A !important;",
      "strong": "font-weight: 600; color: #C2410C !important;",
      "em": "font-style: italic; color: #6B6B6B !important;",
      "a": "color: #C2410C !important; text-decoration: none; border-bottom: 1px solid #C2410C;",
      "ul": "margin: 18px 0; padding-left: 28px;",
      "ol": "margin: 18px 0; padding-left: 28px;",
      "li": "margin: 8px 0; line-height: 1.8 !important; color: #1A1A1A !important;",
      "blockquote": "margin: 20px 0; padding: 12px 18px; background-color: #FFF7ED !important; border-left: 4px solid #C2410C; color: #1A1A1A !important; font-size: 15px; line-height: 1.7 !important; border-radius: 0 4px 4px 0;",
      "code": "font-family: \"JetBrains Mono\", \"SF Mono\", Consolas, monospace; font-size: 14px; padding: 2px 6px; background-color: #F5F5F0 !important; color: #C2410C !important; border-radius: 3px; border: 1px solid #E5E5E5;",
      "pre": "margin: 22px 0; padding: 18px; background-color: #F5F5F0 !important; border: 1px solid #E5E5E5; border-radius: 4px; overflow-x: auto; line-height: 1.6 !important;",
      "hr": "margin: 32px 0; border: none; border-top: 1px solid #E5E5E5;",
      "img": "max-width: 100%; max-height: 500px !important; height: auto; display: block; margin: 22px auto; border-radius: 4px;",
      "table": "width: 100%; margin: 22px 0; border-collapse: collapse; font-size: 15px;",
      "th": "background-color: #F5F5F0 !important; padding: 10px 14px; text-align: left; border: 1px solid #E5E5E5; font-weight: 600; color: #1A1A1A !important;",
      "td": "padding: 10px 14px; border: 1px solid #E5E5E5; color: #1A1A1A !important;",
      "tr": "border-bottom: 1px solid #E5E5E5;"
    },
    "description": "偏文档与说明书质感，适合结构化知识整理和清晰表达。"
  },
  "dracula": {
    "name": "Dracula",
    "description": "暗紫色赛博吸血鬼美学，粉青撞色的视觉冲击",
    "styles": {
      "container": "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #f8f8f2 !important; background-color: #282a36 !important; word-wrap: break-word;",
      "h1": "font-size: 32px; font-weight: 700; color: #bd93f9 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;",
      "h2": "font-size: 26px; font-weight: 600; color: #ff79c6 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
      "h3": "font-size: 21px; font-weight: 600; color: #8be9fd !important; line-height: 1.4 !important; margin: 28px 0 14px;",
      "h4": "font-size: 18px; font-weight: 600; color: #50fa7b !important; line-height: 1.4 !important; margin: 24px 0 12px;",
      "h5": "font-size: 17px; font-weight: 600; color: #f8f8f2 !important; line-height: 1.4 !important; margin: 20px 0 10px;",
      "h6": "font-size: 16px; font-weight: 600; color: #f8f8f2 !important; line-height: 1.4 !important; margin: 18px 0 9px;",
      "p": "margin: 18px 0 !important; line-height: 1.7 !important; color: #f8f8f2 !important;",
      "strong": "font-weight: 700; color: #ffb86c !important;",
      "em": "font-style: italic; color: #8be9fd !important;",
      "a": "color: #8be9fd !important; text-decoration: none; border-bottom: 1px solid #8be9fd; padding-bottom: 1px;",
      "ul": "margin: 16px 0; padding-left: 28px;",
      "ol": "margin: 16px 0; padding-left: 28px;",
      "li": "margin: 8px 0; line-height: 1.7 !important; color: #f8f8f2 !important;",
      "blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #44475a !important; border-left: 4px solid #bd93f9; color: #f8f8f2 !important; border-radius: 4px;",
      "code": "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #44475a !important; color: #50fa7b !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
      "pre": "margin: 24px 0; padding: 20px; background-color: #44475a !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
      "hr": "margin: 36px auto; border: none; height: 1px; background-color: #6272a4 !important; width: 100%;",
      "img": "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
      "table": "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
      "th": "background-color: #44475a !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #bd93f9 !important; border: 1px solid #6272a4;",
      "td": "padding: 12px 16px; border: 1px solid #6272a4; color: #f8f8f2 !important;",
      "tr": "border: none;"
    }
  },
  "bloomberg": {
    "name": "Bloomberg",
    "description": "还原华尔街古老金融终端机，硬派科技代码展示专属",
    "styles": {
      "container": "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: \"SF Mono\", \"Courier New\", Courier, monospace; font-size: 16px; line-height: 1.7 !important; color: #15fa52 !important; background-color: #000000 !important; word-wrap: break-word;",
      "h1": "font-size: 32px; font-weight: 700; color: #fff !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; ",
      "h2": "font-size: 26px; font-weight: 600; color: #eee !important; line-height: 1.35 !important; margin: 32px 0 16px;",
      "h3": "font-size: 21px; font-weight: 600; color: #ddd !important; line-height: 1.4 !important; margin: 28px 0 14px;",
      "h4": "font-size: 18px; font-weight: 600; color: #15fa52 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
      "h5": "font-size: 17px; font-weight: 600; color: #15fa52 !important; line-height: 1.4 !important; margin: 20px 0 10px;",
      "h6": "font-size: 16px; font-weight: 600; color: #15fa52 !important; line-height: 1.4 !important; margin: 18px 0 9px;",
      "p": "margin: 18px 0 !important; line-height: 1.7 !important; color: #15fa52 !important;",
      "strong": "font-weight: 700; color: #15fa52 !important; ",
      "em": "font-style: italic; color: #bbb !important;",
      "a": "color: #ff8c00 !important; text-decoration: none; border-bottom: 1px solid #ff8c00; padding-bottom: 1px;",
      "ul": "margin: 16px 0; padding-left: 28px;",
      "ol": "margin: 16px 0; padding-left: 28px;",
      "li": "margin: 8px 0; line-height: 1.7 !important; color: #15fa52 !important;",
      "blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #0a0a0a !important; border: 1px solid #333; color: #ccc !important; border-radius: 4px; ",
      "code": "font-family: \"SF Mono\", Consolas, monospace; padding: 3px 6px; background-color: #0a0a0a !important; color: #ff8c00 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;",
      "pre": "margin: 24px 0; padding: 20px; background-color: #0a0a0a !important; border: 1px solid #333; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
      "hr": "margin: 36px auto; border: none; height: 1px; background-color: #333 !important; width: 100%;",
      "img": "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
      "table": "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
      "th": "background-color: #0a0a0a !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #15fa52 !important; border: 1px solid #333;",
      "td": "padding: 12px 16px; border: 1px solid #333; color: #15fa52 !important;",
      "tr": "border: none;"
    }
  },
  "cyberpunk": {
    "name": "Cyberpunk",
    "description": "霓虹闪烁的赛博朋克世界，品红与青的极致碰撞",
    "styles": {
      "container": "max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: \"SF Mono\", \"Fira Code\", Consolas, monospace; font-size: 15px; line-height: 1.7 !important; color: #e0e0ff !important; background-color: #0d0221 !important; word-wrap: break-word;",
      "h1": "font-size: 32px; font-weight: 700; color: #ff2a6d !important; text-shadow: 0 0 8px rgba(255,42,109,0.5); line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: 0.05em; text-transform: uppercase;",
      "h2": "font-size: 26px; font-weight: 600; color: #05d9e8 !important; text-shadow: 0 0 8px rgba(5,217,232,0.5); line-height: 1.35 !important; margin: 32px 0 16px;",
      "h3": "font-size: 21px; font-weight: 600; color: #d1f7ff !important; line-height: 1.4 !important; margin: 28px 0 14px;",
      "h4": "font-size: 18px; font-weight: 600; color: #ff2a6d !important; line-height: 1.4 !important; margin: 24px 0 12px;",
      "h5": "font-size: 17px; font-weight: 600; color: #e0e0ff !important; line-height: 1.4 !important; margin: 20px 0 10px;",
      "h6": "font-size: 16px; font-weight: 600; color: #e0e0ff !important; line-height: 1.4 !important; margin: 18px 0 9px;",
      "p": "margin: 18px 0 !important; line-height: 1.7 !important; color: #e0e0ff !important;",
      "strong": "font-weight: 700; color: #ff2a6d !important; text-shadow: 0 0 6px rgba(255,42,109,0.4);",
      "em": "font-style: italic; color: #05d9e8 !important;",
      "a": "color: #05d9e8 !important; text-decoration: none; border-bottom: 1px solid #05d9e8; padding-bottom: 1px;",
      "ul": "margin: 16px 0; padding-left: 28px;",
      "ol": "margin: 16px 0; padding-left: 28px;",
      "li": "margin: 8px 0; line-height: 1.7 !important; color: #e0e0ff !important;",
      "blockquote": "margin: 24px 0; padding: 16px 20px; background-color: #1a0a3e !important; border-left: 4px solid #ff2a6d; color: #c8c8ff !important; border-radius: 0;",
      "code": "font-family: \"SF Mono\", \"Fira Code\", Consolas, monospace; padding: 3px 6px; background-color: #1a0a3e !important; color: #05d9e8 !important; border-radius: 0; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #2a1a4e;",
      "pre": "margin: 24px 0; padding: 20px; background-color: #1a0a3e !important; border-radius: 0; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #2a1a4e;",
      "hr": "margin: 36px auto; border: none; height: 2px; background: linear-gradient(90deg, #ff2a6d, #05d9e8) !important; width: 100%;",
      "img": "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 0;",
      "table": "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 14px;",
      "th": "background-color: #1a0a3e !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #ff2a6d !important; border: 1px solid #2a1a4e;",
      "td": "padding: 12px 16px; border: 1px solid #2a1a4e; color: #e0e0ff !important;",
      "tr": "border: none;"
    }
  },
  "lemonde": {
    "name": "Le Monde 世界报",
    "styles": {
      "container": "max-width: 680px; margin: 0 auto; padding: 20px 20px 45px 20px; font-family: Georgia, \"Times New Roman\", serif; font-size: 17px; line-height: 1.8 !important; color: #2c2c2c !important; background-color: #fffef9 !important; word-wrap: break-word;",
      "h1": "font-size: 32px; font-weight: 400; color: #1a1a1a !important; line-height: 1.2 !important; margin: 36px 0 18px; text-align: center; letter-spacing: -0.02em; font-family: \"Didot\", Georgia, serif; text-transform: uppercase;",
      "h2": "font-size: 26px; font-weight: 300; color: #2c2c2c !important; line-height: 1.3 !important; margin: 32px 0 16px; text-align: center; padding: 14px 0; border-top: 1px solid #2c2c2c; border-bottom: 1px solid #2c2c2c; font-style: italic;",
      "h3": "font-size: 21px; font-weight: 400; color: #2c2c2c !important; line-height: 1.35 !important; margin: 28px 0 14px; padding-left: 16px; position: relative; font-style: italic;",
      "h4": "font-size: 16px; font-weight: 400; color: #3a3a3a !important; line-height: 1.4 !important; margin: 24px 0 12px; letter-spacing: 0.1em; text-transform: uppercase;",
      "h5": "font-size: 16px; font-weight: 400; color: #4a4a4a !important; line-height: 1.45 !important; margin: 20px 0 10px; font-style: italic;",
      "h6": "font-size: 15px; font-weight: 400; color: #5a5a5a !important; line-height: 1.45 !important; margin: 18px 0 9px;",
      "p": "margin: 20px 0 !important; line-height: 1.85 !important; color: #2c2c2c !important; text-align: justify; text-indent: 2em;",
      "strong": "font-weight: 600; color: #1a1a1a !important; letter-spacing: 0.05em;",
      "em": "font-style: italic; color: #2c2c2c !important; letter-spacing: 0.02em;",
      "a": "color: #2c2c2c !important; text-decoration: none; border-bottom: 1px dotted #2c2c2c;",
      "ul": "margin: 20px 0; padding-left: 28px; list-style-type: disc;",
      "ol": "margin: 20px 0; padding-left: 28px; list-style-type: decimal;",
      "li": "margin: 10px 0; line-height: 1.8 !important; color: #2c2c2c !important; padding-left: 28px; position: relative;",
      "blockquote": "margin: 20px auto; padding: 16px 26px; background-color: transparent !important; border-top: 1px solid #2c2c2c; border-bottom: 1px solid #2c2c2c; color: #2c2c2c !important; font-size: 17px; line-height: 1.6 !important; font-style: italic; text-align: center; max-width: 500px; font-family: Georgia, serif;",
      "code": "font-family: \"Courier Prime\", monospace; font-size: 15px; padding: 2px 6px; background-color: #f9f9f9 !important; color: #2c2c2c !important; border: 1px solid #e0e0e0;",
      "pre": "margin: 24px 0; padding: 20px; background-color: #f9f9f9 !important; border: 1px solid #2c2c2c; overflow-x: auto; line-height: 1.6 !important;",
      "hr": "margin: 36px auto; border: none; text-align: center; height: 20px; background: url(\"data:image/svg+xml,%3Csvg width='80' height='20' xmlns='http://www.w3.org/2000/svg'%3E%3Ctext x='40' y='12' text-anchor='middle' font-size='20' fill='%232c2c2c'%3E⁂%3C/text%3E%3C/svg%3E\") no-repeat center; background-size: 80px 20px;",
      "img": "max-width: 100%; max-height: 500px !important; height: auto; display: block; margin: 24px auto; border-radius: 50% 50% 50% 50% / 60% 60% 40% 40%; filter: sepia(10%);",
      "table": "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
      "th": "background-color: transparent !important; padding: 10px 12px; text-align: left; border-top: 2px solid #2c2c2c; border-bottom: 1px solid #2c2c2c; font-weight: 600; color: #2c2c2c !important; font-style: italic; text-transform: uppercase; letter-spacing: 0.05em; font-size: 13px;",
      "td": "padding: 10px 12px; border-bottom: 1px solid #e0e0e0; color: #2c2c2c !important;",
      "tr": "border-bottom: 1px solid #e0e0e0;"
    },
    "description": "更偏深度报道与文化评论，适合长篇叙述和阅读沉浸。"
  }
} as const;

export type RawThemeKey = keyof typeof RAW_THEME_PRESETS;
